### ISSUE TITLE
Styles editor toggle button has visual glitches

### ISSUE THREAD

**Issue by apemberton** [apemberton/outsystems-studio-mac#11]
<img width="264" alt="screen shot 2018-04-08 at 8 18 14 am" src="https://user-images.githubusercontent.com/86439/38467368-695d6112-3b05-11e8-99eb-0487fbd35605.png">

**Comment by apemberton** [comment]
retest on 0.10

**Comment by goborrega** [comment]
This one seems solved. Tested on my mac
