### ISSUE TITLE
Scroll (in tree, properties, screen, etc) from the macbook trackpad or magic mouse is REALLY fast 

### ISSUE THREAD

**Issue by apemberton** [apemberton/outsystems-studio-mac#19]
(hard to scroll and have it stop where we want). Didn’t try other mouses.
On a longer term use (~8hours, split throughout the day in 2 to 4 hour sessions), this was the most annoying thing

**Comment by apemberton** [comment]
https://wiki.winehq.org/Useful_Registry_Keys
UsePreciseScrolling=n is the fix. 
@goborrega please retest on 0.12 or greater.

**Comment by goborrega** [comment]
Yes, it is fixed.

**Comment by apemberton** [comment]
Resolved in 0.12
