### ISSUE TITLE
Minimize, Maximize & Close buttons have visual artifacts

### ISSUE THREAD

**Issue by apemberton** [apemberton/outsystems-studio-mac#8]
<img width="145" alt="screen shot 2018-04-08 at 8 15 29 am" src="https://user-images.githubusercontent.com/86439/38467351-04e41f14-3b05-11e8-9b42-f983c41c08e1.png">

**Comment by apemberton** [comment]
This is a result of using the "windowscodecs" native DLL from Windows. Without that DLL, the buttons appear fine but there are some unimplemented functions in the wine DLL that are required in Studio.

**Comment by apemberton** [comment]
Confirmed that it's the "windowscodecsext" DLL native override specifically. Changing this back to "builtin" gets rid of the issue; just need to test if that introduces others.

**Comment by apemberton** [comment]
retest on 0.10

**Comment by goborrega** [comment]
Looks good. Doesn't seem to have introduced other issues, based on a small test.
